sonar.projectKey=AGG233_sts2-analyzer
sonar.organization=agg233

sonar.projectName=sts2-analyzer
sonar.projectVersion=1.0

sonar.sources=app
sonar.exclusions=**/node_modules/**,**/dist/**,**/.nuxt/**,**/.output/**,**/tests/**,**/docs/**,GAME_SOURCE.md

sonar.tests=tests
sonar.test.inclusions=tests/**/*spec.ts,tests/**/*test.ts

sonar.sourceEncoding=UTF-8