// Locale data loader — imports from separate JSON files, no hardcoded translations.
// UI translations: src/locales/ui/{lang}.json (manually maintained)
// Game translations: src/locales/game/{lang}.json (generated by scripts/sync-locales.ts)

import gameDe from "./game/de.json";
import gameEn from "./game/en.json";
import gameEs from "./game/es.json";
import gameFr from "./game/fr.json";
import gameIt from "./game/it.json";
import gameJa from "./game/ja.json";
import gameKo from "./game/ko.json";
import gamePl from "./game/pl.json";
import gamePt from "./game/pt.json";
import gameRu from "./game/ru.json";
import gameTh from "./game/th.json";
import gameTr from "./game/tr.json";
import gameZh from "./game/zh.json";
import uiEn from "./ui/en.json";
import uiJa from "./ui/ja.json";
import uiKo from "./ui/ko.json";
import uiZh from "./ui/zh.json";

export const en = { ui: uiEn, game: gameEn };
export const zh = { ui: uiZh, game: gameZh };
export const ja = { ui: uiJa, game: gameJa };
export const ko = { ui: uiKo, game: gameKo };
export const de = { ui: uiEn, game: gameDe };
export const fr = { ui: uiEn, game: gameFr };
export const es = { ui: uiEn, game: gameEs };
export const it = { ui: uiEn, game: gameIt };
export const pl = { ui: uiEn, game: gamePl };
export const pt = { ui: uiEn, game: gamePt };
export const ru = { ui: uiEn, game: gameRu };
export const tr = { ui: uiEn, game: gameTr };
export const th = { ui: uiEn, game: gameTh };

export type LocaleMessages = typeof en;
