// Lookup helpers: translate game IDs to localized display names
// Game data translations live in src/locales/game/{lang}.json (generated by sync-locales)
// Access pattern: t('game.{category}.{KEY.title|KEY.name}', fallback)

// Map CHARACTER.X → characters.X.title
export function characterKey(id: string): string {
	return `${id.replace("CHARACTER.", "")}.title`;
}

// Map CARD.X → cards.X.title
export function cardKey(id: string): string {
	return `${id.replace("CARD.", "")}.title`;
}

// Map RELIC.X → relics.X.title
export function relicKey(id: string): string {
	return `${id.replace("RELIC.", "")}.title`;
}

// Map ENCOUNTER.X → encounters.X.title
export function encounterKey(id: string): string {
	return `${id.replace("ENCOUNTER.", "")}.title`;
}

// Map MONSTER.X → monsters.X.name
export function monsterKey(id: string): string {
	return `${id.replace("MONSTER.", "")}.name`;
}

// Map ACT.X → acts.X.title
export function actKey(id: string): string {
	return `${id.replace("ACT.", "")}.title`;
}

// Map map_point_type → map.X.title
export function mapPointTypeKey(type: string): string {
	const mapping: Record<string, string> = {
		monster: "LEGEND_ENEMY.title",
		elite: "LEGEND_ELITE.title",
		boss: "LEGEND_BOSS.title",
		event: "LEGEND_EVENT.title",
		shop: "LEGEND_MERCHANT.title",
		treasure: "LEGEND_TREASURE.title",
		rest_site: "LEGEND_REST.title",
		ancient: "LEGEND_ANCIENT.title",
		unknown: "LEGEND_UNKNOWN.title",
	};
	return mapping[type] ?? type;
}

// Short type label for timeline (not translated, always abbreviated)
export function mapPointTypeShort(type: string): string {
	const short: Record<string, string> = {
		monster: "MON",
		elite: "ELI",
		boss: "BOSS",
		event: "EVT",
		shop: "SHOP",
		treasure: "TRS",
		rest_site: "REST",
		ancient: "ANC",
		unknown: "???",
	};
	return short[type] ?? type;
}

// Map ENCHANTMENT.X → enchantments.X.title
export function enchantmentKey(id: string): string {
	return `${id.replace("ENCHANTMENT.", "")}.title`;
}

// Map game_mode (lowercase) → game_modes.SINGLE_PLAYER_{MODE}.title
export function gameModeKey(mode: string): string {
	return `SINGLE_PLAYER_${mode.toUpperCase()}.title`;
}

// Map rest site choice → rest_site_ui.OPTION_{CHOICE}.name
export function restSiteChoiceKey(choice: string): string {
	return `OPTION_${choice}.name`;
}

// Map EVENT.X → events.X.title (event name lookup)
export function eventKey(id: string): string {
	return `${id.replace("EVENT.", "")}.title`;
}

// Map POTION.X → potions.X.title
export function potionKey(id: string): string {
	return `${id.replace("POTION.", "")}.title`;
}

const modelIdPrefixRegex = /^(ENCOUNTER|EVENT|ANCIENT)\./;

// Composable for component use
export function useGameI18n() {
	const { t, te } = useI18n();

	// Resolve a model_id (ENCOUNTER.X, EVENT.X, ANCIENT.X, etc.) to a translated name
	// Searches encounters → events → ancients in order
	function modelIdName(id: string): string {
		const bare = id.replace(modelIdPrefixRegex, "");
		const tables = ["encounters", "events", "ancients"];
		for (const table of tables) {
			const path = `game.${table}.${bare}.title`;
			if (te(path)) return t(path);
		}
		return bare;
	}

	function cardDescription(id: string): string {
		const bare = id.replace("CARD.", "");
		const path = `game.cards.${bare}.description`;
		return t(path, "");
	}

	return {
		t,
		te,
		modelIdName,
		characterName: (id: string) =>
			t(`game.characters.${characterKey(id)}`, id.replace("CHARACTER.", "")),
		cardName: (id: string) =>
			t(`game.cards.${cardKey(id)}`, id.replace("CARD.", "")),
		cardDescription,
		relicName: (id: string) =>
			t(`game.relics.${relicKey(id)}`, id.replace("RELIC.", "")),
		encounterName: (id: string) =>
			t(`game.encounters.${encounterKey(id)}`, id.replace("ENCOUNTER.", "")),
		monsterName: (id: string) => {
			// 首先尝试完整的 id
			const fullKey = `game.monsters.${monsterKey(id)}`;
			if (te(fullKey)) {
				return t(fullKey);
			}
			// 如果失败，尝试去掉 _FRONT/_MIDDLE/_BACK 后缀
			const baseId = id.replace(/_(FRONT|MIDDLE|BACK)$/, "");
			const baseKey = `game.monsters.${monsterKey(baseId)}`;
			if (te(baseKey)) {
				return t(baseKey);
			}
			// 都没有找到，返回原始 id
			return id.replace("MONSTER.", "");
		},
		actName: (id: string) =>
			t(`game.acts.${actKey(id)}`, id.replace("ACT.", "")),
		mapTypeName: (type: string) => t(`game.map.${mapPointTypeKey(type)}`, type),
		mapTypeShort: mapPointTypeShort,
		enchantmentName: (id: string) =>
			t(
				`game.enchantments.${enchantmentKey(id)}`,
				id.replace("ENCHANTMENT.", ""),
			),
		gameModeName: (mode: string) =>
			t(`game.game_modes.${gameModeKey(mode)}`, mode),
		restSiteChoiceName: (choice: string) =>
			t(`game.rest_site_ui.${restSiteChoiceKey(choice)}`, choice),
		eventName: (id: string) =>
			t(`game.events.${eventKey(id)}`, id.replace("EVENT.", "")),
		potionName: (id: string) =>
			t(`game.potions.${potionKey(id)}`, id.replace("POTION.", "")),
	};
}
